Class {
	#name : #FmxSQLUnknownSourceLanguage,
	#superclass : #FmxSQLSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'FamixNGSQL-Entities'
}

{ #category : #meta }
FmxSQLUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FmxSQLSourceLanguage>
	<package: #FamixNGSQL>
	<generated>
	^self
]
