"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `anchorsOnIntervalsOfCode` | `FmxSQLTWithEntitySourceAnchor` | `entity` | `FmxSQLEntitySourceAnchor` | |



"
Trait {
	#name : 'FmxSQLBehaviouralEntity',
	#traits : 'FmxSQLTWithEntitySourceAnchor',
	#classTraits : 'FmxSQLTWithEntitySourceAnchor classTrait',
	#category : 'FamixNGSQL-Traits',
	#package : 'FamixNGSQL',
	#tag : 'Traits'
}

{ #category : 'meta' }
FmxSQLBehaviouralEntity classSide >> annotation [

	<ignoreForCoverage>
	<FMClass: #BehaviouralEntity super: #Object>
	<package: #FamixNGSQL>
	<generated>
]
