"
I am a join clause


"
Class {
	#name : 'FmxSQLJoinClause',
	#superclass : 'FmxSQLClause',
	#category : 'FamixNGSQL-Entities',
	#package : 'FamixNGSQL',
	#tag : 'Entities'
}

{ #category : 'meta' }
FmxSQLJoinClause class >> annotation [

	<ignoreForCoverage>
	<FMClass: #JoinClause super: #FmxSQLClause>
	<package: #FamixNGSQL>
	<generated>
]

{ #category : 'testing' }
FmxSQLJoinClause >> isJoinClause [

	<ignoreForCoverage>
	<generated>
	^ true
]
