"
I am a limit clause


"
Class {
	#name : 'FmxSQLLimitClause',
	#superclass : 'FmxSQLClause',
	#category : 'FamixNGSQL-Entities',
	#package : 'FamixNGSQL',
	#tag : 'Entities'
}

{ #category : 'meta' }
FmxSQLLimitClause class >> annotation [

	<ignoreForCoverage>
	<FMClass: #LimitClause super: #FmxSQLClause>
	<package: #FamixNGSQL>
	<generated>
]

{ #category : 'testing' }
FmxSQLLimitClause >> isLimitClause [

	<ignoreForCoverage>
	<generated>
	^ true
]
